.gitignore, project/production.py
Raven settings give errors. These should be handled by configuration management in local_settings.py anyways.
=> Changes made in deployment

hkm/templates/hkm/views/search.html
Small change to sort authors and date in ascending order.
=> Sort the results on the search page in order

hkm/views.py
Instead of doing a query for every record fetch users favorite records as list of ids once.
=> Fetch favorite records once.

hkm/static/hkm/js/hkm-v2.js, hkm/templates/hkm/base.html, hkm/templates/hkm/snippets/search_records_grid.html, hkm/templates/hkm/views/search.html, hkm/templates/hkm/views/search_record.html, hkm/views.py
Make search return 1...n pages by adding a 'page' parameter.
Save unique record anchor into localStorage on record visit and scroll back to it when returning to search results.
=> Scroll search results to recently visited record.

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_navbar.scss
- In the navigation rework commit, a bootstrap class was modified which broke accordion functionality.
- Also removed unused css.
=> Fix accordion not collapsing

hkm/templates/hkm/views/search_record.html, hkm/views.py
Calculate and add a page parameter for search button in record view.
=> Add page paramater for "return to search" button

hkm/templates/hkm/snippets/search_records_grid.html
Just as in bb68e2d. Show "era" instead of a "year" value.
=> Show record year in search result list.

.gitlab-ci.yml
Added the necessary Gitlab parameters for configuring the application's base domain URL in review/staging/production environments. The parameter is used e.g. when a shareable URL of an image is requested by the user.
=> Add domain config

.gitlab-ci.yml
Had typos in all of the Bambora related env var names. Fixed those.
=> HEL-29 | Fix Bambora env variable names

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/base_viewer.html, hkm/templates/hkm/views/order.html, hkm/templates/hkm/views/order_contact_information.html
- Image + order detail layout and font changes.
- Increased title size in search images and browse album
=> HEL-119 | Image + order detail page style changes

hkm/templatetags/hkm_tags.py
Previously if "Show on front page" album had only one record it would crash the application.
=> HEL-115 | Fix front page crash

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/base_viewer.html
- Moved `rawData.description` to it's own row.
- Fixed fonts in single image "card".
=> HEL-119 | Fix single image fonts.

hkm/views/views.py
- Limit `RESULTS_PER_PAGE` to 40.
- Clear session after browser is closed
- Fixed issue where pressing "Load more" would duplicate all previous images every time button was pressed.
=> HEL-52 | Fix issue where "Load more" would copy all previous images

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/views/home_page.html
Fix fonts and margins in showcases.
=> HEL-112 | Fix fonts and margins in showcases.

hkm/views/views.py
- Added back previous line deleted line, where `self.search_results` is set from session
- Added extra check for "Load more" functionality. If user presses search button multiple times, session won't duplicate itself endlessly.
=> HEL-52 | Fix crashing caused by session not being restored

docker-compose.env.example.yaml, kuvaselaamo/settings.py
Added a slightly better formatting to the logging and added a possibility to
change the log level using an environment variable (defaults to ERROR).
=> Add possibility to configure log levels with env variable

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss
Tweaked margins a little bit and increased size of the album description.
=> HEL-171 | Margin tweaks

hkm/static/hkm/js/hkm-v2.js, hkm/views/views.py, kuvaselaamo/settings.py, requirements.in, requirements.txt
I added the necessary configuration for getting the staging environment to
work with GCS. I tested this locally and was able to fix the previous issues
when saving images using InMemoryUploadedFile. Turned out that when the image
was written into memory, a StringIO buffer was used so that the buffer was
pointing at the end of the image which in turn was interpreted by the storage
library so that there was no image to read. I fixed this by including seek(0)
statements before the InMemoryUploadedFile was created.
I also added a quick fix for the "crop and download" UI so that the download
is at least started. The browser is now handling it as a popup, since I used
window.open() to get it going. This should probably be fixed at some point.
I also added the environment variable configuration …
=> HEL-188 | Add GCS configuration

hkm/views/views.py, kuvaselaamo/settings.py, requirements.in, requirements.txt
Turn of GSC override, now the images with duplicate names get random ID string.
Added unidecode package to change non-english characters.
=> HEL-191 | Turn of GSC override, remove non-english characters

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/base_browse.html, hkm/templates/hkm/views/collection.html, hkm/templates/hkm/views/order.html, hkm/templates/hkm/views/order_contact_information.html, hkm/templates/hkm/views/order_summary.html, hkm/templates/hkm/views/public_collections.html, hkm/templates/hkm/views/search.html
Removed `.row` class and moved most of the padding changes to `fullsize-container`, this makes it easier to control them across the application. 
Improved mobile usability:
- Paddings for mobile
- Min height for images in search page & album images. This makes sure that images are always somewhat visible.
- Fixed problem where actions popover was hidden under `.back-to` container.
=> HEL-195 | Mobile fixes

hkm/management/commands/create_initial_page_content.py, hkm/templates/hkm/snippets/navigation.html, hkm/templatetags/hkm_tags.py, hkm/urls.py, hkm/views/views.py
In last PR I forgot to delete all the stuff related to old `index.html`. I also renamed the url name to `hkm_home`.
=> HEL-182 | Remove stuff related to old index.html

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/static/hkm/scss/_navbar.scss, hkm/static/hkm/scss/bootstrap/_variables.scss
This PR fixes few breakpoints, there are a lot of changes, because I needed to change one bootstrap variable to make sure header collapses before it splits into multiple rows due insufficient width.
I also increased `min-height` in hero area, to give text a little more space.
Increased footer breakpoint to match those used with margins across the application, logos no longer overflow and break the layout.
=> HEL-171 | Fix breakpoints

hkm/views/views.py
If user is in `/search/record/` path and changes language, application should no longer show text that "Finna is not respoding". Instead correct image is shown.
=> HEL-213 | Fix url params

hkm/templates/hkm/views/info.html, hkm/views/views.py
Normal feedback form (found in footer) now shows message after form is submitted.
=> HEL-215 | Normal feedback form shows success message

hkm/static/hkm/css/main.css, hkm/static/hkm/js/basket.js, hkm/static/hkm/scss/_app.scss, hkm/static/hkm/scss/_basket-page.scss, hkm/templates/hkm/views/_basket_content.html, hkm/templates/hkm/views/basket.html
Shopping cart is now responsive.
=> HEL-209 | Make shopping cart responsive

hkm/views/views.py
Fix issue where search term containing non ascii letters would crash the application.
=> HEL-229 | Fix application crash with search term containing non ascii letters

CHANGELOG.md, hkm/views/checkout.py, hkm/views/views.py
- Created a class for checkout that holds the language data. (This might be a little overkill, but at at least I don't need to copy same stuff to multiple places)
- Changed `BasketView` to extend `BaseView`, language information is now passed to that class as well.
=> HEL-225 | Fix logos missing from basket and checkout pages

CHANGELOG.md, hkm/templates/hkm/base_viewer.html, hkm/templatetags/hkm_tags.py
As described in the [HEL-184](https://helsinkisolutionoffice.atlassian.net/browse/HEL-184), some of the fields had excess commas at the end of the line, these are now removed
=> HEL-184 | Remove excess commas

CHANGELOG.md, hkm/templates/hkm/emails/feedback.txt
Removed extra linefeed symbols
=> HEL-164 | Remove extra linefeed symbols

CHANGELOG.md
Merge release branch back to develop.
=> [develop] Release 2.2.0

CHANGELOG.md, hkm/static/hkm/css/main.css, hkm/static/hkm/js/hkm-v2.js, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/base_viewer.html, hkm/urls.py, hkm/views/views.py
Removed cropper from add to collection modal and moved the methods under `AjaxAddToCollection` class.
=> HEL-206 | Streamline add to collection

CHANGELOG.md, hkm/templates/hkm/base.html
Commented out the part where missing ios-icon was required.
=> HEL-120 | Fix missing ios-icon error

CHANGELOG.md, hkm/management/commands/clean_unused_data.py, hkm/models/models.py
Added `clean_unused_data` script that removes data. Time period can me modified using `days` parameter. Tested this locally and it worked just fine.
=> HEL-247 | Remove unused data script

.github/workflows/staging.yml, CHANGELOG.md, Dockerfile
Added a kubernetes cron job that will run `clean_unused_data` script and `clearsessions`. This change will only work on our new pipeline.
EDIT:
Also made changes to `Dockerfile` there was problem installing `requirements-prod.txt`
=> HEL-248 | Clean up unused data automatically

README.md
Fixes readme so we can merge to develop and update the staging instance.
=> Chore | Fix readme

requirements-dev.in, requirements-dev.txt, requirements-prod.in, requirements-prod.txt
Moved `google-cloud-storage` package from `requirements-dev.txt` to `requirements-prod.txt`.
This should fix the issue where build crashes.
=> Move google-storage to prod

.github/workflows/staging.yml
=> FIX | Cronjob secret value

requirements.txt
Reverts City-of-Helsinki/kuvaselaamo#42
Forgot to change branch to develop
=> Revert "Bump pyyaml from 3.12 to 5.1"

.github/workflows/review.yml, .github/workflows/staging.yml, .gitignore, README.md, browser-tests/.env.example, browser-tests/enable-dotenv.js, browser-tests/pages/LandingPage.ts, browser-tests/smokeTest.ts, browser-tests/utils/route.ts, browser-tests/utils/settings.ts, package-lock.json, package.json
Adds the simplest possible test case and runs it when changes are made into PR or staging environments.
In this case, the test checks that the landing page of the application is online.
=> Run smoke e2e tests against PR and staging deployments

.github/workflows/production.yml
I added the necessary configuration to run the cleanup commands in production
using a Cronjob. The job runs daily at midnight.
=> HEL-263 | Configure cleanup job in production

hkm/templatetags/hkm_tags.py, hkm/utils.py
=> Fix the encoding of the return link  from zoomed picture

hkm/management/commands/create_initial_page_content.py
HEL-313: Remove Bambora and Printmotor from privacy statement.
=> Update the privacy statement

hkm/tests/test_clean_unused_data.py, hkm/tests/test_signals.py
HEL-311. Fix naive datetimes in tests
=> Update tests to be timezone aware

hkm/static/hkm/js/hkm-v2.js, hkm/templates/hkm/snippets/search_records_grid.html, hkm/templates/hkm/views/search_record.html, hkm/views/views.py
- Fix JS for load more functionality
- Browse to last viewed picture in search results feature caused an JS error
- Changing language removed non-ascii letters from the search terms
=> HEL-311 | Some minor fixes

hkm/management/commands/fetch_record_id_mapping.py, hkm/migrations/0047_update_record_ids.py
Implement a management command to retrieve id mapping information to a json file and a migration to use the mapping file to update the record ids in the database.
=> HEL-329 | Update record ids

CHANGELOG.md, browser-tests/.env.example, docker-compose.yml, hkm/finna.py, hkm/models/models.py, hkm/templates/hkm/base.html, hkm/templates/hkm/base_viewer.html, hkm/templates/hkm/views/info.html, hkm/templatetags/hkm_tags.py, hkm/views/views.py, requirements.txt, setup.cfg
Return previously removed feedback functionality.
Fix full resolution image downloads.
Replace google analytics with matomo.
Implement minor updates to photo details layout.
=> Hel 328 hel 331 hel 332 | Feedbacks, full resolution download and matomo

azure-pipelines-kuvaselaamo-release.yml, azure-pipelines-kuvaselaamo-review.yml, azure-pipelines-kuvaselaamo-test.yml, k6LoadTests.js
[DEVOPS-479](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-479)
=> DevOps pipelines and k6 loadtest configuration

hkm/static/hkm/js/hkm-v2.js, hkm/templates/hkm/snippets/login.html
Fixes issues HEL-270 for clearing out dated error messages by re-applying 'hidden' css class as needed and HEL-271 correcting the error message rendering using as_ul.
=> Hel 271 hel 270 UI fixes

browser-tests/utils/route.ts, hkm/finna.py, hkm/models/models.py, hkm/templates/hkm/views/collection.html, hkm/templates/hkm/views/collection_record.html, hkm/templates/hkm/views/search_record.html, hkm/templatetags/hkm_tags.py, hkm/views/views.py, package.json
=> Hel 334 hel 340 photo size handling

hkm/finna.py, hkm/management/commands/fetch_record_id_mapping.py
Update museoliitto server references to use HTTPS.
=> chore: update Museoliitto server url

hkm/admin.py
=> fix: collection admin search
