hkm/static/hkm/js/hkm-v2.js
Instead of checking for last_record_browsed value check that $item element exists.
=> Fix scrollToLastItem function

hkm/templates/hkm/base_viewer.html
Based on users feedback exact year may be misleading.
Use "era" value instead.
=> Show photo's era instead of exact year.

hkm/templates/hkm/base_viewer.html
Seems like api does not always have photos era OR year, for example https://hkm.finna.fi/Record/hkm.HKMS000005:0000000f
So default to empty string if era is not available.
=> Fix default value of photos year.

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss
add max-height to svg-icon which should fix ie11 issues
refs HEL-161
=> Fix ie11 svg logo height on search page

hkm/static/hkm/js/hkm-v2.js
Currently, the load more button hangs on loading if there are no more results or if there is a server error. This is a quick fix meant to show feedback when there aren't any new search results received from Finna.
Todo: Improve error handling and language checking.
=> Add check for loading button in case of no results

hkm/management/commands/create_initial_page_content.py
"Browse collections" was not working because there were initially no
public collections which were set to be on display. I changed the
initialization script so that the default collection is created with
proper attributes.
=> HEL-32 | Fix initialization of the default collection

.prod/on_deploy.sh, README.md, docker-entrypoint.sh, hkm/management/commands/add_admin_user.py
Changed the default admin username to kuva-admin so that if/when the
database is initialized with the existing data dump from the old site,
our init scripts will create a separate superuser that we can use.
=> HEL-18 | Change default admin username

.gitignore, .gitlab-ci.yml, docker-compose.env.example.yaml, kuvaselaamo/settings.py, requirements.in, requirements.txt
Added the necessary things in order to get email sending to work using XO's Mailgun service:
- Added django-anymail to the application (had to use an ancient version to
avoid having to change the current Django version)
- Updated the requirements
- Added suitable environment variables to settings
- Added examples of the environment variables to docker config
- Added the environment variables to the Gitlab configs.
=> HEL-27 | Add Mailgun configuration to the application

hkm/forms.py, hkm/templates/hkm/snippets/search_records_grid.html, hkm/templates/hkm/views/search_record.html, hkm/templatetags/hkm_tags.py, hkm/views/views.py
Search results are now saved in session. If link is copied from address bar and no session is found, image is fetched from finna based on `image_id` parameter. In this case previous and next arrows + "Back to search results" button is hidden.
"Image detail view" allows user to move to previous and next image. This view uses images found in session and does not fetch more if last image is reached (this is logic might be improved later).
Also cleaned up some unused imports.
=> HEL-52 | Fix image permanent link

hkm/models/models.py, hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/templates/hkm/views/home_page.html
- `is_public` is set automatically true if `is_showcaseable` is true
- Frontpage showcases show museum logo
- In "Browse albums" view, album owner is now displayed with correct color & font
=> HEL-112 | Fix collections and fonts

hkm/templates/hkm/base.html, kuvaselaamo/locale/en/LC_MESSAGES/django.po, kuvaselaamo/locale/fi/LC_MESSAGES/django.po, kuvaselaamo/locale/sv/LC_MESSAGES/django.po
Adds accessibility statement link to footer. The page itself is already created in the helsinkikuvia with 'hkm_siteinfo_accessibility' identifier.
=> Add accessibility statement page link to footer

hkm/templates/hkm/views/siteinfo_accessibility.html, hkm/urls.py, hkm/views/views.py
Noticed that these were missing from the initial implementation. To accessibility page to work it needs the url and view. Template is not 100% necessary, but every other page has it so it's there.
=> Add misssing url, view and template to accessibility page

hkm/templates/hkm/views/home_page.html, hkm/templatetags/hkm_tags.py, hkm/views/views.py
Change the way the front page determines what is displayed as the owner of
a showcased collection. Earlier this used the is_featured flag of a Collection,
but the more logical solution is to do this automatically by checking if the
owner of the displayed Collection is a staff member or not. If they are staff,
the Helsinki logo is displayed. Otherwise the user icon + username.
I also added some prefetching in the queries to lessen the number of db
queries on the frontpage.
=> HEL-127 | Change showcase owner display logic

hkm/models/models.py
When a user opens their own album's record, they will now get the same full
resolution image URL as the rest of the views. The URL points to the proxy
server which has larger resolution images than the ones which were used in
the own album view earlier.
[HEL-174](https://helsinkisolutionoffice.atlassian.net/browse/HEL-174)
Tested manually on the developer's environment.
1. Login as a user who has an own album with an image
2. Click "Own albums"
3. Select one of your albums
4. Select one of the images inside
5. Click on "Download full resolution image"
6. Verify that the link points to http://89.250.56.218/KDKDataProvider/(something) and that it returns an image.
=> HEL-178 | Point full res image URL to proxy server in all record views

hkm/views/views.py
The latest changes contained a typo. The app was trying to query Finna with
record ids instead of Finna ids. I fixed this now.
=> HEL-174 | Fix typo in field name

hkm/templates/hkm/base_viewer.html, hkm/views/views.py
After these changes record stays as favourite after page refresh. I also fixed other bug: If favourites collection contained single image and it was removed in record detail view, it would show as a favourite when returning to search list.
In previous PR where I refactored record actions, I didn't notice that image URL was set in contex so I removed the duplicate URL fetching.
=> HEL-207 | Fix favourite not updating after refresh

hkm/models/models.py, hkm/templates/hkm/views/collection.html, hkm/templatetags/hkm_tags.py, hkm/views/views.py
When the app is displaying a collections' records list, it needs to know
what records are marked as a favorite by the currently logged in user.
Earlier this was done in the template by calling `Record.is_favorite()`
which then made database queries. This resulted in 2*(num of records)
queries for every collection details view. The queries are quite fast
so the user would not experience a lot of delay because of them, but
they were still unnecessary.
I changed this now so that the favorites are fetched only once in the
view's setup phase. The view marks the listed records with `is_favorite`
which is then used by the template.
I also removed the now-obsolete `Record.is_favorite()` to prevent this from
happening again.
=> HEL-54 | Stop repeating favorites queries in collection view

hkm/static/hkm/js/hkm-v2.js
Previously if user was one of their albums and edit was toggled, "buy" button was on top of the delete button. Now, when edit is toggled, buy button is hidden from the view.
=> HEL-204 | Hide buy button if album edit is toggled

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_navbar.scss, hkm/templates/hkm/base_viewer.html, hkm/templates/hkm/snippets/nav_basket_counter.html, hkm/templates/hkm/views/my_collections.html
In this PR I made little tweaks to layout.
- [HEL-216](https://helsinkisolutionoffice.atlassian.net/browse/HEL-216) In Own albums view, I removed `container` class to align page to the left with correct margings. 
- [HEL-196](https://helsinkisolutionoffice.atlassian.net/browse/HEL-196) When mobile navigation is toggled, correctly show `Shopping cart text`, I also aligned `User` text and icon. I also removed paddings from the wrapper and moved them to logo and menu button instead. Mobile menu width is now correctly 100%.
- [HEL-58](https://helsinkisolutionoffice.atlassian.net/browse/HEL-58) When adding new image to album, user was required to delete the `New album` text before typing anything. I moved this text to placeholder to improve usability.
=> HEL-216, HEL-196, HEL-58 | Style fixes

hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_app.scss, hkm/static/hkm/scss/_navbar.scss, hkm/templates/hkm/snippets/nav_basket_counter.html
- Added `min-width` to search button, text should no longer overflow if text is in english.
- Shopping cart text in mobile menu now has enough space to keep text in one line.
=> HEL-196, HEL-218 | Improve mobile layout

hkm/finna.py, hkm/urls.py, hkm/views/views.py
The previous production version of the app was referring to single images as
`(base url)/search/record/?search=some-search-term&page=123` which meant that
the app would do a Finna query with `some-search-term`, pick the 123rd result
and display it to the user.
Now that we've modified the search logic, these links are invalid. They are
however still used, probably in some Google caches or similar, so we've been
getting a lot of such requests in production since launching the service in
Kuva infra.
Our modified search was still using the `/search/record` URL, but it was
expecting an `image_id` parameter which was not being given by the old-style
links. This caused the app to query Finna without the record id, resulting in
a 400 error from Finna.
I've now changed the app's logic so that the …
=> HEL-232 | Prevent invalid Finna queries

CHANGELOG.md, hkm/urls.py, hkm/views/views.py
There are currently at least some users and/or services which use the older
versions of image urls to point to image details hosted by our service. We
want to support those urls so the users' links won't get broken.
This PR adds backwards support for the older urls so that the incoming
request redirects to the newer version of the url using a permanent redirect
(301). Basically `/record/<finna_id>/` gets translated to
`/search/details/?image_id=<finna_id>`.
=> HEL-233 | Add support for legacy image urls

CHANGELOG.md, hkm/log_filters.py, hkm/views/views.py, kuvaselaamo/settings.py
Earlier our logging configuration only logged the basic message for each log
entry. Many log entries in the app however are adding extra data into each
entry using the `extra` dictionary parameter, but we couldn't add that data
into the log because those entries without the extra data would crash with a
`KeyError`.
I added a new log filter which ensures that the logged `LogRecord` will
always have the property `data` which is now used in the log formatter so
that we can see the extra data in the logs.
=> HEL-240 | Configure extra data in log entries

hkm/urls.py
The url `record/feedback` was not working, since the last change overrode its
url mapping. I changed the order so that it works and the rest of the similar
urls will go to the legacy mapping `record/<finna_id>`.
=> HEL-233 | Fix record's feedback url

hkm/views/checkout.py
I missed one class when I was fixing logos last time. `OrderConfirmation` now extends `BaseCheckoutView` and should get the language attribute.
=> HEL-225 | Order confirmation was still missing logos

CHANGELOG.md, hkm/views/views.py
"Browse albums" used to fetch all public collections which it would display
on the view as users' public albums. The featured albums were separated into
their own list by picking collections marked with `is_featured`. These were
then displayed separately on the view.
I changed this so that the users' public collections do not contain those
which are marked with `is_featured` so that the two lists do not contain
duplicate entries.
=> HEL-238 | Remove duplicate collections from "browse albums" view

hkm/templates/hkm/views/search_record.html, hkm/views/views.py
Back to search option ended up being hidden when user navigated from search view to image details view.
Search option is shown when application detects that `previous/ next` record is present, if these are absent, user has used direct link and search option is hidden.
=> HEL-234 | Restore back to search option

hkm/views/views.py
Added `record.index` back, it was apparently used to show image number inside "Back to search" part.
=> HEL-234 | Add index back

CHANGELOG.md
Some entries from release 2.1.0 were missing from the changelog. Here they are.
=> Add missing entries to CHANGELOG

CHANGELOG.md, hkm/views/views.py
Previously I reworked `record.index` logic to use `for loop`'s index. This caused counting to start always at 1 which resulted in showing wrong information in "back to search" section. 
This should now be fixed, if session has records and "Load more" is pressed, it starts at correct position.
[HEL-245](https://helsinkisolutionoffice.atlassian.net/browse/HEL-245)
=> HEL-245 | Fix record index logic

CHANGELOG.md, hkm/finna.py
This PR removes head query that was made to determine if image has high quality version. Finna functions differently from the Proxy server, and always returns `OK 200` even if image is missing.
[HEL-243](https://helsinkisolutionoffice.atlassian.net/browse/HEL-243)
=> HEL-243 | Remove head query

CHANGELOG.md, hkm/static/hkm/css/main.css, hkm/static/hkm/scss/_navbar.scss
Header layout was broken on safari. After these changes it behaves the same way as Chrome and Firefox.
vs
=> HEL-244 | Header layout is broken on safari

CHANGELOG.md, hkm/apps.py, hkm/auditlog_signals.py, kuvaselaamo/settings.py
The app was not creating any log for login attempts which might make it more
vulnerable to misuse.
I added some signal handlers for login events so that they are now logged to
console whose output is in turn sent to a centralized service where the log
entries may be viewed.
The following levels are used:
- failed login: warning
- succeeded login: info
- logout: debug
The configuration is set to log INFO and above.
=> HEL-224 | Log outcomes of login attempts

CHANGELOG.md, hkm/templates/hkm/views/home_page.html, hkm/templates/hkm/views/my_collections.html, hkm/templates/hkm/views/public_collections.html
Due the missing translations on collection titles, `lang="fi"` attribute was added to all collections. It will force screen reader to read titles in finnish.
Manual testing instructions:
Using screen reader
1. Navigate to home page -> showcase collection titles should be read in finnish.
2. Navigate to "Explore albums" page -> title should be read in finnish.
3. Navigate to "Own albums" -> again titles should be read in finnish. When user creates favourite album the first time, its language is determined by users current language at the time. Favourites album should be read with the users current language.
=> HEL-150 | Browsing collections is challenging with screen reader

hkm/management/commands/clean_unused_data.py, hkm/models/models.py
Made a change to `clean_unused_data` script. Super users and staff are no longer deleted. I could't figure out a better way to do this. Before this change goes to into use, we need to make sure that all correct accounts are market as staff.
=> HEL-247 | Restrict which users are deleted

hkm/finna.py, hkm/templates/hkm/snippets/search_records_grid.html, hkm/templatetags/hkm_tags.py
Finna does not support providing the size parameters `w` and `h` anymore when fetching images. Remove the size parameters from the request.
=> Remove size parameters from Finna image requests

.prod/uwsgi.ini, CHANGELOG.md
Healthz and readiness endpoints are requested continuously by our infra. This
creates an awful lot of unnecessary log.
I disabled the logging for the endpoints using uwsgi configs.
=> HEL-258 | Disable logging for /healthz and /readiness

CHANGELOG.md, hkm/views/views.py
When I upgraded django version from 1.10 to 1.11, `RequestContext` method was changed and was not returning an object. I used provided `.flatten()` to fix this issue.
=> HEL-264 | Fix shopping cart

CHANGELOG.md, hkm/templates/hkm/views/_basket_content.html
Earlier the shopping basket view was displaying the actual full resolution
images from Finna for each line in the order. This meant that the browser
fetched several megabytes from Finna only to display the images as small
thumbnails. In addition, the thumbnails contained the whole image and not
the actual cropped part which the user had selected, probably causing a lot
of confusion about what the user was ordering.
The cropped image's url was already made available when the basket was
displayed, so I just changed the view to use the cropped image's url
instead of the Finna url.
=> HEL-42 | Show cropped images in shopping basket view

docker-compose.env.example.yaml, kuvaselaamo/settings.py
Django defaults to 3 days when determining the validity period of a password
reset link. This is too much for us, so I added an environment variable for
controlling this value. The value defaults to 1 but it can now be changed if
necessary.
=> HEL-125 | Add environment variable for pwd reset link validity period

browser-tests/.env.example, browser-tests/albumFeature.ts, browser-tests/imageFeature.ts, browser-tests/mainSearchFeature.ts, browser-tests/pages/AlbumListPage.ts, browser-tests/pages/AlbumPage.ts, browser-tests/pages/ImageDetailsPage.ts, browser-tests/pages/LandingPage.ts, browser-tests/pages/Navigation.ts, browser-tests/pages/SearchPage.ts, browser-tests/utils/route.ts
Adds browser tests that check that the search on the landing page can be used to find images, albums can be used to find images, and that the image page contains the content we expect.
=> HEL-276, HEL-277 | Add browser test that cover a few important user paths

.gitlab-ci.yml, docker-compose.env.example.yaml, hkm/models/models.py
There was still one remaining `send_main` function with old `HKM_FEEDBACK_FROM_EMAIL`. 
I changed this to `docker-compose.env.example.yaml ` + `.gitlab-ci.yaml` as well.
=> HOTFIX | Fix from email variable to orders.

hkm/models/models.py, hkm/tests/test_signals.py
When we've sent a notification to a user telling that their account will be
deleted after one month, the user can "cancel" the scheduled deletion by
logging in to the service.
I added a signal handler which sets a user's `removal_notification_sent`
field to null after login. This will affect the scheduled removal so that the
user won't be considered for deletion until 11 months later, if they don't
login before that. At that point, they will get a new notification and their
`removal_notification_sent` is set again.
=> HEL-263 | Clear removal notification timestamp after login

.github/workflows/staging.yml, hkm/management/commands/clean_unused_data.py, hkm/management/commands/send_removal_notifications.py, hkm/tests/factories.py, hkm/tests/settings.py, hkm/tests/test_send_removal_notifications.py
Added the new management command `send_removal_notifications` which will
send an email notification to users who have not logged in in a while (=
335 days by default or a custom value if given as a parameter) and who
have not yet received a notification. Also added tests for the command.
I changed the staging environment's config so that the new command will run
before `clean_unused_data`.
See the detailed instructions in the ticket: https://helsinkisolutionoffice.atlassian.net/browse/HEL-263
This has now been tested locally according to the ticket + the tests are passing.
=> HEL-263 | Add new management command for sending removal notifications

.github/workflows/staging.yml
The initial amount of email notifications in production is estimated to be
~1500. Sending that many emails takes over 5 minutes at least in staging
which means that the default value for max duration (5 minutes) is too low.
We want to keep the job running to avoid errors and duplicate emails which
is what is happening in staging, so I bumped this up to 15 minutes.
=> HEL-263 | Add max duration to staging's cronjob

CHANGELOG.md, hkm/management/commands/send_removal_notifications.py, hkm/tests/test_send_removal_notifications.py
We currently have some invalid email addresses in our user database and
we are not verifying the new users' emails, so we're bound to get more typos
in emails in the future. These invalid addresses caused the scheduled
notification run to crash when it encountered such an address, therefore
stopping the whole notification process.
I added a check which makes sure that when Mailgun responds with a 400 Bad
request, the run will just mark that user as having been sent the message
and continues with the run. If we have a wrong address for a user, then they
are anyway unable to request for a password reset and so their user account
can't be accessed.
I also added a test for this + changed the commands status printouts a bit.
This has been tested by running the unit tests + locally by …
=> HEL-288 | Skip invalid emails when sending removal notifications

.github/workflows/ci.yml, .github/workflows/staging.yml
We are abandoning `develop` branch in favor of Gitflow (= everything is
done in `master`).
I changed the deployment configs to trigger from master branch from now on.
=> HEL-294 | Change development process to Gitflow

hkm/templatetags/hkm_tags.py
When there are no "show on front page" collections, as was the case in
production a while ago, the app shows a default image. For some reason
we had a typo in the image's url and we noticed it only in production
after the frontpage collections were removed via a scheduled.
I fixed the typo, so now the default image works in case there is a
similar issue in production.
=> HEL-298 | Fix typo in default front page image url

CHANGELOG.md, hkm/templatetags/hkm_tags.py
For some reason `data` under `format` is returning a string instead of a `dict`. I need to contact Finna to make sure if this is a bug or not. For now I just added a type check to fix application from crashing.
Viewing a single image will throw error on test + production: [test here](https://helsinkikuvia.fi/search/details/?image_id=hkm.HKMS000005:km0000lh18)
Error fixed on [PR env](https://kuvaselaamo-fix-image-type-translation-243.test.kuva.hel.ninja/search/details/?image_id=hkm.HKMS000005:km0000lh18)
=> Fix | image_type translation

requirements.txt
HEL-311. Updated psycopg2 to v.2.9.3 to fix issues on Mac OS platform.
=> Updated psycopg2

hkm/static/hkm/js/cookie-consent.js, hkm/templates/hkm/base.html
Always require cookie consent but remove requirement for general tracking consent ("requireConsent"). Set cookie consent given if consent cookie is "1" and when cookie consent is clicked as accepted. Latter is probably unnecessary due to this not being a SPA. Cookies written to '/' to be effective throughout the site.
=> fix: matomo cookieless tracking

hkm/admin.py
HEL-353. Add list display columns, filters and search fields to Django admin site views to make administration easier.
=> feat: improve django admin site views

.dockerignore, Dockerfile, docker-compose.yml, docker-entrypoint.sh
also remove deprecated version number from docker-compose.yml:
"the attribute `version` is obsolete, it will be ignored, please remove
it to avoid potential confusion"
refs HEL-349
[HEL-349](https://helsinkisolutionoffice.atlassian.net/browse/HEL-349)
[HEL-349]: https://helsinkisolutionoffice.atlassian.net/browse/HEL-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HEL-349 | Use Red Hat UBI Python image in Docker

docker-compose.yml
The PostgreSQL version used by the production database
psql-hel-platta-prod-001 is currently v13.12, so upgrading the
PostgreSQL version in docker-compose.yml to the nearest available
minor version i.e. v13.13.
Using Amazon ECR Public Registry as the Docker image source instead of
Docker Hub as the latter's rate limits were changed during summer 2024
and have been causing problems as of late.
refs HEL-351
[HEL-351](https://helsinkisolutionoffice.atlassian.net/browse/HEL-351)
[HEL-351]: https://helsinkisolutionoffice.atlassian.net/browse/HEL-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HEL-351 | Update PostgreSQL to v13.13 in docker-compose.yml
